### ISSUE TITLE
Wheels are built without OMP

### ISSUE THREAD

**Issue by arokem** [MacPython/dipy-wheels#1]
https://travis-ci.org/MacPython/dipy-wheels/jobs/110804158#L583

**Comment by matthew-brett** [comment]
OSX Clang / gcc doesn't have omp . Some comments here : http://stackoverflow.com/questions/26159225/openmp-support-in-xcode-6-clang-3-5

**Comment by arokem** [comment]
But it's possible to get an OMP-enabled c compiler using homebrew, with a
little bit of contorting:

https://github.com/nipy/dipy/pull/739#issuecomment-150998525

**Comment by matthew-brett** [comment]
Yes, but that might be some work to get right.  Issues I can think of:
- You'd have to care about building for 32-bit and 64-bit.  OSX clang does this by default;
- You'd have to ship the runtime libraries for the compiler, again both 32- and 64-bit.

It can probably be done, but it would be a fair amount of work.

**Comment by matthew-brett** [comment]
For example, I just installed `clang-omp`, and the OMP runtime library is x64_64 only:

```
$ lipo -info /usr/local/Cellar/libiomp/20150701/lib/libiomp5.dylib 
Non-fat file: /usr/local/Cellar/libiomp/20150701/lib/libiomp5.dylib is architecture: x86_64
```

**Comment by arokem** [comment]
Yeah - agreed. More pain than it's worth. If you want to run massive computation, you can easily get your hands on a linux machine.

**Comment by matthew-brett** [comment]
Or recompile yourself for 64-bit only with `clang-omp`...

**Comment by arokem** [comment]
Closing...
