### ISSUE TITLE
Updating dipy submodule

### ISSUE THREAD

**Issue by arokem** [MacPython/dipy-wheels#2]
It's currently pointing to a rather old commit. Is that a problem for uploading a new version (0.11 is registered and tagged, and zip/tar uploaded to pypi!)? How do I update that?

**Comment by arokem** [comment]
Also, how do I know whether a wheel that is currently in the wheelhouse has the right content?

**Comment by matthew-brett** [comment]
See: https://travis-ci.org/MacPython/dipy-wheels/jobs/110804158#L257 and https://github.com/MacPython/dipy-wheels#which-dipy-commit-does-the-repository-build

**Comment by arokem** [comment]
Great - thanks for the help! I think we managed to get it right for the wheels on pypi for 0.11. Closing...
